-- 코드를 입력하세요

WITH Q AS 
(
    SELECT 
        WRITER_ID
    FROM
        USED_GOODS_BOARD
    GROUP BY
        WRITER_ID
    HAVING
        COUNT(*) >= 3
)
    
SELECT 
    USER_ID, 
    NICKNAME, 
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소,
    CONCAT(SUBSTR(U.TLNO, 1, 3), '-', SUBSTR(U.TLNO, 4, 4), '-', SUBSTR(U.TLNO, 8, 4)) 전화번호
FROM
    USED_GOODS_USER U JOIN Q ON U.USER_ID = Q.WRITER_ID
ORDER BY USER_ID DESC

