-- 코드를 입력하세요
WITH A AS
(SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS FROM REST_INFO
WHERE ADDRESS LIKE '서울%')

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE FROM A INNER JOIN REST_REVIEW AS B ON A.REST_ID = B.REST_ID
GROUP BY A.REST_NAME 
ORDER BY SCORE DESC, FAVORITES DESC