-- 코드를 입력하세요

WITH Q AS (SELECT 
    A.FLAVOR, A.TOTAL_ORDER
FROM
    FIRST_HALF AS A
    LEFT JOIN JULY AS B ON A.SHIPMENT_ID = B.SHIPMENT_ID
UNION
SELECT 
    B.FLAVOR, B.TOTAL_ORDER
FROM
    FIRST_HALF AS A
    RIGHT JOIN JULY AS B ON A.SHIPMENT_ID = B.SHIPMENT_ID)

SELECT 
    FLAVOR FROM Q
GROUP BY 
    FLAVOR
ORDER BY 
    SUM(TOTAL_ORDER) DESC LIMIT 3
# ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC LIMIT 3