-- 코드를 입력하세요
SELECT
    P.CATEGORY,
    P.PRICE AS MAX_PRICE,
    P.PRODUCT_NAME
FROM
    FOOD_PRODUCT P
    JOIN (SELECT CATEGORY, MAX(PRICE) AS PRICE FROM FOOD_PRODUCT GROUP BY CATEGORY) AS A
    ON P.CATEGORY = A.CATEGORY
WHERE
    P.PRICE = A.PRICE AND
    P.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY
    MAX_PRICE DESC